### ISSUE TITLE
Not mining

### ISSUE THREAD

**Issue by skobuv1** [2nthony/macmineable#28]
Hi there, 
I have new OSX Monterey 12.0.1, I've downloaded new and older versions of macMineable, set up everything, however it seem not working. I've checked Activity monitor and there is no usage rate for CPU.

Older version says Calculating, newer says Running.

**Comment by 2nthony** [comment]
Check `xmrig` is running in activity monitor, or see the log(left by stop button) on macMineable.

**Comment by skobuv1** [comment]
I've checked, no xmrig, even put CPU usage to 80% to be sure.

**Comment by 2nthony** [comment]
![image](https://user-images.githubusercontent.com/19513289/140706965-8a2d2234-3835-4085-9c21-74c65490f0dd.png)

I am not sure but it works for me and so many users.

---

What is your model?(include, CPU type)

**Comment by skobuv1** [comment]
It's MacBook Pro (15-inch, 2018), 2,2 GHz 6-Core Intel Core i7, 16 GB 2400 MHz DDR4.

Don't know where the problem could be, but appreciate your effort

**Comment by 2nthony** [comment]
can you take the log screenshot to me?

![image](https://user-images.githubusercontent.com/19513289/140867800-0efee6c6-f38c-4d37-9719-d71e12b1e5e6.png)

**Comment by skobuv1** [comment]
There is nothing there really. Left it to work for hour before the screen. I've put Coinbase wallet and also tried the classic coinbase app address, tried multiple coins
<img width="397" alt="Screenshot 2021-11-09 at 13 31 42" src="https://user-images.githubusercontent.com/40527009/140925283-6422590a-f328-4332-83be-464c55e23393.png">
.

**Comment by 2nthony** [comment]
Not sure what reason is. Looks like the `xmrig` can not run.

Try to check the app size, it should around `19.6MB`.

**Comment by skobuv1** [comment]
So the app after unpacking is 9.4 MB and there is nothing under the path 
<img width="543" alt="Screenshot 2021-11-09 at 15 04 25" src="https://user-images.githubusercontent.com/40527009/140938190-1ddd842a-1675-4b4a-a56c-42cb65d26e94.png">

**Comment by 2nthony** [comment]
So the reason is the miner program is been deleted. Try to re-download app and figure why and who delete it, perhaps is your defence app or sth.

![image](https://user-images.githubusercontent.com/19513289/140938930-ac387cca-3103-4112-81ea-74d24c73b706.png)

**Comment by skobuv1** [comment]
You were right! I didnt get any notifications of blocking, but turned off Avast and it is working now.

Thank you

**Comment by 2nthony** [comment]
So we can close this issue now.
