### ISSUE TITLE
Work XRP mining

### ISSUE THREAD

**Issue by Cramos70** [2nthony/macmineable#39]
Hello,
I have started mining XRP 3 days ago and still got weak results. What I noticed when looking at the logs, is that the program stops while the screen is locked or not being used. How can I have it running independently from the screen, please? The results I'm having are just ridiculous. Can you help me?

**Comment by 2nthony** [comment]
I don't think this is the app itself can do, but try this?

![image](https://user-images.githubusercontent.com/19513289/158002233-0d139888-5844-4541-88ab-b473fc7650f2.png)

**Comment by Cramos70** [comment]
Yes, I don’t think is from the app as well. I just wanted to know what could I do for the display. I’ll look for what you suggested. Thank you a million.

Dr. Marcos R. Costa, DDS,OMFS
________________________________

**Comment by 2nthony** [comment]
Yeah, I think just don't let our system get sleep.
