### ISSUE TITLE
现在不要更新了吗

### ISSUE THREAD

**Issue by belugaming** [2nthony/macmineable#45]
开发者您好，请问现在不更新了吗

**Comment by 2nthony** [comment]
自从我更换到 m1 设备的 mac 之后我本地用不了了，所以不做不确定的事也不再更新了

**Comment by belugaming** [comment]
啊这，我正在M1上用啊

2nthony ***@***.***>于2024年7月4日 周四16:57写道：

**Comment by 2nthony** [comment]
那可能是当时我网络问题用不了吧，连不上没去细研究
